name: Generate terraform documentation
on:
  - pull_request
jobs:
  docs:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          working-dir: .,env/prod,env/dev,modules/argocd-password,modules/eks-argocd-cluster,modules/network
          output-file: README.md
          output-method: inject
          git-push: "true"
